### ISSUE TITLE
D4D_FONT_IX type

### ISSUE THREAD

**Issue by faghio** [Gargy007/eGUI#13]
I guess the following declaration:

```c
typedef D4D_TCHAR D4D_FONT_IX;
```

within d4d_font.h, active when D4D_UNICODE is defined, should be changed into:

```c
typedef Word D4D_FONT_IX;
```

otherwise if you configure D4D_WCHAR (= D4D_TCHAR) 4 bytes long, reading of a binary font file produced by the eGUI Converter Utility won't work (fields of type D4D_FONT_IX are 2 bytes long in the file).

**Comment by Gargy007** [comment]
Hi,
 good point, but I think that this should be bug in converter utility.
 This line should make eGUI ready for 4bytes long UNICODE.

What do you think?


Petr

2015-06-01 18:17 GMT+02:00 faghio <notifications@github.com>:

**Comment by Gargy007** [comment]
This is not bug, just eGUI is ready for the 4 bytes UNICODE format, but the converter is not.

So don't use this option (D4D_WCHAR == long == 4 bytes), since the converter utility will be updated.

**Comment by faghio** [comment]
OK. Thank you.
The problem is the arm gcc compiler standard libraries expects 4 bytes wchar_t so you cannot compile with D4D_WCHAR = 2 bytes.
Anyway I can apply that "dirty" fix above for my purposes, while waiting for future releases of the eGUI converter. I don't know how you are involved in that utility, but it would be nice to have the sources of it too, for example to add new features like font antialiasing.
